"""Added dbos systemdb tables

Revision ID: 5d85bad5f7b0
Revises: 
Create Date: 2024-07-19 18:04:34.802185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d85bad5f7b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.create_schema("dbos", create_if_not_exists=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_status',
    sa.Column('workflow_uuid', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('authenticated_user', sa.Text(), nullable=True),
    sa.Column('assumed_role', sa.Text(), nullable=True),
    sa.Column('authenticated_roles', sa.Text(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executor_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(EXTRACT(epoch FROM now()) * 1000::numeric)::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(EXTRACT(epoch FROM now()) * 1000::numeric)::bigint'), nullable=False),
    sa.Column('application_version', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Text(), nullable=True),
    sa.Column('class_name', sa.String(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('config_name', sa.String(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('recovery_attempts', sa.BigInteger(), server_default=sa.text("'0'::bigint"), nullable=False),
    sa.PrimaryKeyConstraint('workflow_uuid'),
    schema='dbos'
    )
    op.create_table('operation_outputs',
    sa.Column('workflow_uuid', sa.Text(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_uuid'], ['dbos.workflow_status.workflow_uuid'], ),
    sa.PrimaryKeyConstraint('workflow_uuid', 'function_id'),
    schema='dbos'
    )
    op.create_table('workflow_inputs',
    sa.Column('workflow_uuid', sa.Text(), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_uuid'], ['dbos.workflow_status.workflow_uuid'], ),
    sa.PrimaryKeyConstraint('workflow_uuid'),
    schema='dbos'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_inputs', schema='dbos')
    op.drop_table('operation_outputs', schema='dbos')
    op.drop_table('workflow_status', schema='dbos')
    # ### end Alembic commands ###
